name: Build and Test - Swasth Backend

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven (using build profile and H2)
        run: mvn clean install -Dspring.profiles.active=build
        env:
          # JWT properties
          JWT_SECRET: dummy_jwt_secret
          TOKEN_EXPIRATION_TIME: 600000
          REFRESH_TOKEN_EXPIRATION_TIME: 1200000

          # Mail properties (dummy)
          MAIL_USERNAME: dummy@gmail.com
          MAIL_PASSWORD: dummy_password

          # OAuth properties (dummy)
          GOOGLE_CLIENT_ID: dummy_google_client_id
          GOOGLE_CLIENT_SECRET: dummy_google_client_secret
          GOOGLE_REDIRECT_URI: http://localhost:3000/oauth2/callback/google

          GITHUB_CLIENT_ID: dummy_github_client_id
          GITHUB_CLIENT_SECRET: dummy_github_client_secret
          GITHUB_REDIRECT_URI: http://localhost:3000/oauth2/callback/github

          # Frontend URL
          FRONTEND_URL: http://localhost:3000
