name: Build and Test - Swasth Backend

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: test_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -u root -ppassword"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Wait for MySQL to be ready
        run: |
          echo "Waiting for MySQL to be healthy..."
          for i in {1..30}; do
            if mysqladmin ping -h 127.0.0.1 -u root -ppassword --silent; then
              echo "✅ MySQL is up!"
              break
            fi
            sleep 2
          done

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: swasth-jar
          path: target/swasth-id-backend-*.jar # update this to your actual jar name
